# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
#import sys
import myiter
import test
from PyQt5 import QtCore, QtGui, QtWidgets
hijri=1
month="june"
form=2
flag=1
days=20
def change(h,m,fo,fl,d):
    global hijri
    global month
    global form
    global flag
    global days
    hijri=h
    month=m
    form=fo
    flag=fl
    days=d

class Ui_Form(object):


    def warning(self,title,message):
        mess=QtWidgets.QMessageBox()

        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()

        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(502, 323)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        #self.spinBox = QtWidgets.QSpinBox(Form)
        #self.spinBox.setObjectName("spinBox")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setObjectName("textEdit_1")
        self.verticalLayout.addWidget(self.textEdit_1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout.addWidget(self.doubleSpinBox)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.pg_gen)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Student name"))
        self.label_2.setText(_translate("Form", "Select current Surat"))
        self.comboBox.setItemText(0, _translate("Form", "الفاتحة"))
        self.comboBox.setItemText(1, _translate("Form", "البقرة"))
        self.comboBox.setItemText(2, _translate("Form", "آل عمران"))
        self.comboBox.setItemText(3, _translate("Form", "النساء"))
        self.comboBox.setItemText(4, _translate("Form", "المائدة"))
        self.comboBox.setItemText(5, _translate("Form", "الأنعام"))
        self.comboBox.setItemText(6, _translate("Form", "الأعراف"))
        self.comboBox.setItemText(7, _translate("Form", "الأنفال"))
        self.comboBox.setItemText(8, _translate("Form", "التوبة"))
        self.comboBox.setItemText(9, _translate("Form", "يونس"))
        self.comboBox.setItemText(10, _translate("Form", "هود"))
        self.comboBox.setItemText(11, _translate("Form", "يوسف"))
        self.comboBox.setItemText(12, _translate("Form", "الرعد"))
        self.comboBox.setItemText(13, _translate("Form", "إبراهيم"))
        self.comboBox.setItemText(14, _translate("Form", "الحجر"))
        self.comboBox.setItemText(15, _translate("Form", "النحل"))
        self.comboBox.setItemText(16, _translate("Form", "الإسراء"))
        self.comboBox.setItemText(17, _translate("Form", "الكهف"))
        self.comboBox.setItemText(18, _translate("Form", "مريم"))
        self.comboBox.setItemText(19, _translate("Form", "طه"))
        self.comboBox.setItemText(20, _translate("Form", "الأنبياء"))
        self.comboBox.setItemText(21, _translate("Form", "الحج"))
        self.comboBox.setItemText(22, _translate("Form", "المؤمنون"))
        self.comboBox.setItemText(23, _translate("Form", "النور"))
        self.comboBox.setItemText(24, _translate("Form", "الفرقان"))
        self.comboBox.setItemText(25, _translate("Form", "الشعراء"))
        self.comboBox.setItemText(26, _translate("Form", "النمل"))
        self.comboBox.setItemText(27, _translate("Form", "القصص"))
        self.comboBox.setItemText(28, _translate("Form", "العنكبوت"))
        self.comboBox.setItemText(29, _translate("Form", "الروم"))
        self.comboBox.setItemText(30, _translate("Form", "لقمان"))
        self.comboBox.setItemText(31, _translate("Form", "السجدة"))
        self.comboBox.setItemText(32, _translate("Form", "الأحزاب"))
        self.comboBox.setItemText(33, _translate("Form", "سبأ"))
        self.comboBox.setItemText(34, _translate("Form", "فاطر"))
        self.comboBox.setItemText(35, _translate("Form", "يس"))
        self.comboBox.setItemText(36, _translate("Form", "الصافات"))
        self.comboBox.setItemText(37, _translate("Form", "ص"))
        self.comboBox.setItemText(38, _translate("Form", "الزمر"))
        self.comboBox.setItemText(39, _translate("Form", "غافر"))
        self.comboBox.setItemText(40, _translate("Form", "فصلت"))
        self.comboBox.setItemText(41, _translate("Form", "الشورى"))
        self.comboBox.setItemText(42, _translate("Form", "الزخرف"))
        self.comboBox.setItemText(43, _translate("Form", "الدخان"))
        self.comboBox.setItemText(44, _translate("Form", "الجاثية"))
        self.comboBox.setItemText(45, _translate("Form", "الأحقاف"))
        self.comboBox.setItemText(46, _translate("Form", "محمد"))
        self.comboBox.setItemText(47, _translate("Form", "الفتح"))
        self.comboBox.setItemText(48, _translate("Form", "الحجرات"))
        self.comboBox.setItemText(49, _translate("Form", "ق"))
        self.comboBox.setItemText(50, _translate("Form", "الذاريات"))
        self.comboBox.setItemText(51, _translate("Form", "الطور"))
        self.comboBox.setItemText(52, _translate("Form", "النجم"))
        self.comboBox.setItemText(53, _translate("Form", "القمر"))
        self.comboBox.setItemText(54, _translate("Form", "الرحمن"))
        self.comboBox.setItemText(55, _translate("Form", "الواقعة"))
        self.comboBox.setItemText(56, _translate("Form", "الحديد"))
        self.comboBox.setItemText(57, _translate("Form", "المجادلة"))
        self.comboBox.setItemText(58, _translate("Form", "الحشر"))
        self.comboBox.setItemText(59, _translate("Form", "الممتحنة"))
        self.comboBox.setItemText(60, _translate("Form", "الصف"))
        self.comboBox.setItemText(61, _translate("Form", "الجمعة"))
        self.comboBox.setItemText(62, _translate("Form", "المنافقون"))
        self.comboBox.setItemText(63, _translate("Form", "التغابن"))
        self.comboBox.setItemText(64, _translate("Form", "الطلاق"))
        self.comboBox.setItemText(65, _translate("Form", "التحريم"))
        self.comboBox.setItemText(66, _translate("Form", "الملك"))
        self.comboBox.setItemText(67, _translate("Form", "القلم"))
        self.comboBox.setItemText(68, _translate("Form", "الحاقة"))
        self.comboBox.setItemText(69, _translate("Form", "المعارج"))
        self.comboBox.setItemText(70, _translate("Form", "نوح"))
        self.comboBox.setItemText(71, _translate("Form", "الجن"))
        self.comboBox.setItemText(72, _translate("Form", "المزمل"))
        self.comboBox.setItemText(73, _translate("Form", "المدثر"))
        self.comboBox.setItemText(74, _translate("Form", "القيامة"))
        self.comboBox.setItemText(75, _translate("Form", "الإنسان"))
        self.comboBox.setItemText(76, _translate("Form", "المرسلات"))
        self.comboBox.setItemText(77, _translate("Form", "النبأ"))
        self.comboBox.setItemText(78, _translate("Form", "النازعات"))
        self.comboBox.setItemText(79, _translate("Form", "عبس"))
        self.comboBox.setItemText(80, _translate("Form", "التكوير"))
        self.comboBox.setItemText(81, _translate("Form", "الإنفطار"))
        self.comboBox.setItemText(82, _translate("Form", "المطففين"))
        self.comboBox.setItemText(83, _translate("Form", "الانشقاق"))
        self.comboBox.setItemText(84, _translate("Form", "البروج"))
        self.comboBox.setItemText(85, _translate("Form", "الطارق"))
        self.comboBox.setItemText(86, _translate("Form", "الأعلى"))
        self.comboBox.setItemText(87, _translate("Form", "الغاشية"))
        self.comboBox.setItemText(88, _translate("Form", "الفجر"))
        self.comboBox.setItemText(89, _translate("Form", "البلد"))
        self.comboBox.setItemText(90, _translate("Form", "الشمس"))
        self.comboBox.setItemText(91, _translate("Form", "الليل"))
        self.comboBox.setItemText(92, _translate("Form", "الضحى"))
        self.comboBox.setItemText(93, _translate("Form", "الشرح"))
        self.comboBox.setItemText(94, _translate("Form", "التين"))
        self.comboBox.setItemText(95, _translate("Form", "العلق"))
        self.comboBox.setItemText(96, _translate("Form", "القدر"))
        self.comboBox.setItemText(97, _translate("Form", "البينة"))
        self.comboBox.setItemText(98, _translate("Form", "الزلزلة"))
        self.comboBox.setItemText(99, _translate("Form", "العاديات"))
        self.comboBox.setItemText(100, _translate("Form", "القارعة"))
        self.comboBox.setItemText(101, _translate("Form", "التكاثر"))
        self.comboBox.setItemText(102, _translate("Form", "العصر"))
        self.comboBox.setItemText(103, _translate("Form", "الهمزة"))
        self.comboBox.setItemText(104, _translate("Form", "الفيل"))
        self.comboBox.setItemText(105, _translate("Form", "قريش"))
        self.comboBox.setItemText(106, _translate("Form", "الماعون"))
        self.comboBox.setItemText(107, _translate("Form", "الكوثر"))
        self.comboBox.setItemText(108, _translate("Form", "الكافرون"))
        self.comboBox.setItemText(109, _translate("Form", "النصر"))
        self.comboBox.setItemText(110, _translate("Form", "المسد"))
        self.comboBox.setItemText(111, _translate("Form", "الإخلاص"))
        self.comboBox.setItemText(112, _translate("Form", "الفلق"))
        self.comboBox.setItemText(113, _translate("Form", "الناس"))
        self.label_3.setText(_translate("Form", "Current ayat"))
        self.label_4.setText(_translate("Form", "Pages per day"))
        self.pushButton.setText(_translate("Form", "Generate"))

    def pg_gen(self):
        try:
            name=self.textEdit.toPlainText()
            
            n=float(self.doubleSpinBox.text())
            sur=self.comboBox.currentText()
            x=int(self.textEdit_1.toPlainText())
            if(name=="" or n==0.0):
                raise Exception()
            for i in myiter.sup:
                if(sur==i):
                    sur=myiter.sup.index(i)
            yr=myiter.to_arab(hijri)
            v=test.line_search2(x,sur,n,days)
            myiter.to_excel1(v,days,form,name,n,month,yr)
            print("\nTakhteet added in excel sheet")
            self.messagebox("Alert","Takhteet added successfully")
        except:
            self.warning("Alert","Enter valid credentials")
    
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

